### ISSUE TITLE
Port mongo-tx to unicorn

### ISSUE THREAD

**Issue by haifengl** [hhorii/mongo-transaction#2]
Hi,

This is a very nice work! We have a open source project [unicorn](https://github.com/haifengl/unicorn), which provides a document & graph data model on top of BigTable (currently supports HBase, Cassandra, Accumulo, and RocksDB). The system is purely on client side and the API is compatible with MongoDB. Can you please port mongo-tx to unicorn? If you need any helps, please let me know. Thank you very much in advance!

Bests,
Haifeng

**Comment by hhorii** [comment]
sorry. I do not have any plans to port MongoTx to the other opensource projects.
